#!/usr/bin/env python3
"""
Utility to visualize a single residue graph generated by graph_generation.py.

Nodes with label 1 (proline) are drawn in red; nodes with label 0 are drawn in
black. The plot uses the C-alpha coordinates (3D scatter) and draws peptide-bond
edges.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (required for 3D projection)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize a single protein residue graph (JSONL entry)."
    )
    parser.add_argument(
        "--graph-file",
        required=True,
        type=Path,
        help="Path to JSONL file produced by graph_generation.py.",
    )
    parser.add_argument(
        "--structure-id",
        type=str,
        default=None,
        help="Specific structure_id to visualize (defaults to first entry).",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=None,
        help="If provided, save the figure to this path instead of showing.",
    )
    return parser.parse_args()


def load_graph(graph_file: Path, structure_id: str | None) -> Dict:
    """Return the first graph (or matching structure_id) from JSONL."""
    with graph_file.open("r", encoding="utf-8") as handle:
        for line in handle:
            entry = json.loads(line)
            if structure_id is None or entry.get("structure_id") == structure_id:
                return entry
    raise ValueError(
        f"Structure '{structure_id}' not found in {graph_file}"
        if structure_id
        else f"No graphs found in {graph_file}"
    )


def extract_coordinates(nodes: List[Dict]) -> Tuple[List[float], List[float], List[float]]:
    """Return separate x,y,z coordinate lists."""
    xs, ys, zs = [], [], []
    for node in nodes:
        x, y, z = node["ca_coord"]
        xs.append(x)
        ys.append(y)
        zs.append(z)
    return xs, ys, zs


def visualize_graph(graph: Dict, output_path: Path | None) -> None:
    nodes = graph["nodes"]
    edges = graph["edges"]
    xs, ys, zs = extract_coordinates(nodes)

    colors = ["red" if node.get("label", 0) == 1 else "black" for node in nodes]
    labels = [node.get("label", 0) for node in nodes]

    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(xs, ys, zs, c=colors, s=35, depthshade=True)

    for idx, node in enumerate(nodes):
        ax.text(xs[idx], ys[idx], zs[idx], str(labels[idx]), color="white", fontsize=6)

    for src, dst in edges:
        x_line = [xs[src], xs[dst]]
        y_line = [ys[src], ys[dst]]
        z_line = [zs[src], zs[dst]]
        ax.plot(x_line, y_line, z_line, color="gray", linewidth=1, alpha=0.6)

    ax.set_title(f"Structure: {graph['structure_id']}")
    ax.set_xlabel("X (Å)")
    ax.set_ylabel("Y (Å)")
    ax.set_zlabel("Z (Å)")

    plt.tight_layout()
    if output_path is None:
        plt.show()
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, dpi=300)
        print(f"Saved visualization to {output_path}")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    graph_file = args.graph_file.expanduser().resolve()
    if not graph_file.exists():
        raise FileNotFoundError(f"Graph file not found: {graph_file}")

    graph = load_graph(graph_file, args.structure_id)
    visualize_graph(graph, args.output_path)


if __name__ == "__main__":
    main()

